// // @ts-check

// // This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// /**
//  * Creating a sidebar enables you to:
//  - create an ordered group of docs
//  - render a sidebar for each doc of that group
//  - provide next/previous navigation

//  The sidebars can be generated from the filesystem, or explicitly defined here.

//  Create as many sidebars as you want.

//  @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
//  */
// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     'intro',
//     'hello',
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['tutorial-basics/create-a-document'],
//     },
//   ],
//    */
// };

// export default sidebars;

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  textbookSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: [
        'intro/overview',
        'intro/learning-outcomes',
      ],
    },

    {
      type: 'category',
      label: 'Physical AI Foundations',
      items: [
        'physical-ai/what-is-physical-ai',
        'physical-ai/embodied-intelligence',
        'physical-ai/why-physical-ai-matters',
      ],
    },

    {
      type: 'category',
      label: 'ROS 2 – Robotic Nervous System',
      items: [
        'ros2/ros2-overview',
        'ros2/nodes-topics-services',
        'ros2/urdf-introduction',
      ],
    },

    {
      type: 'category',
      label: 'Simulation & Digital Twin',
      items: [
        'simulation/digital-twin',
        'simulation/gazebo',
        'simulation/unity',
        'simulation/sensor-simulation',
      ],
    },

    {
      type: 'category',
      label: 'NVIDIA Isaac Platform',
      items: [
        'nvidia-isaac/isaac-sim',
        'nvidia-isaac/isaac-ros',
        'nvidia-isaac/sim-to-real',
      ],
    },

    {
      type: 'category',
      label: 'Vision–Language–Action (VLA)',
      items: [
        'vla/vision-language-action',
        'vla/voice-to-action',
        'vla/cognitive-planning',
      ],
    },

    {
      type: 'category',
      label: 'Capstone Project',
      items: [
        'capstone/project-overview',
        'capstone/system-workflow',
        'capstone/expected-outcomes',
      ],
    },
  ],
};

export default sidebars;
